#LISTA DE DATOS
numeros=[1,2,3,4,5]

#ACCEDER A TODOS LOS DATOS DE LA LISTA AL MISMO TIEMPO
print(numeros)

#ACCEDER A UN SOLO ELEMENTO DE LA LISTA
print(numeros[0])

#ACCEDER DE FOMRA INDIVIDUAL A CADA ELEMENTO DE UNA LISTA
for numero in numeros:
    print(numero + 10)